#!/bin/bash



case "$1" in
    purge|remove)
        # 彻底清除：删除所有配置和数据文件
	echo "remove files of fde"
	sudo waydroid session stop 1>/dev/null 2>&1 
	sudo systemctl daemon-reload 2>/dev/null
	sudo systemctl stop openfde-infra 1>/dev/null 2>&1
	sudo systemctl stop waydroid-container 1>/dev/null 2>&1
	sudo rm -rf /usr/share/waydroid-extra/images 1>/dev/null 2>&1
	sudo rm -rf /usr/bin/fde_utils 1>/dev/null 2>&1
	sudo rm -rf /var/lib/waydroid/ 1>/dev/null 2>&1
	sudo rm -rf /usr/lib/waydroid/ 1>/dev/null 2>&1
	sudo rm -rf /usr/bin/fde_ctrl 1>/dev/null 2>&1
	sudo rm -rf /usr/bin/fde_fs 1>/dev/null 2>&1
	sudo rm -rf /usr/bin/fde_brightness 1>/dev/null 2>&1
	sudo rm -rf /var/lib/fde 1>/dev/null 2>&1
        ;;
    upgrade)
        # 升级：保留旧数据，准备新版本
        #echo "正在升级到新版本..."
        # 可以在这里备份旧版本数据
        ;;

    failed-upgrade)
        # 升级失败：可能需要回滚
        ;;

    *)
        ;;
esac

exit 0


