#!/bin/bash

#step 1 install fde
echo 10 > /tmp/fde_installing_process
if [ -e /usr/bin/fde_ctrl ];then
	sudo mv /usr/bin/fde_ctrl /tmp/fde_ctrl&& sudo rm -rf /tmp/fde_ctrl
fi
if [ -e /usr/bin/fde_fs ];then
	sudo mv /usr/bin/fde_fs /tmp/fde_fs && sudo rm -rf /tmp/fde_fs
fi
echo "Step 2: config environments"
sudo tar -xf /usr/openfde/fde.tar -C /
sudo rm -rf /usr/openfde/fde.tar
sudo sysctl -p
echo 15 >> /tmp/fde_installing_process

sudo rm -rf /usr/share/xsessions/mutter.desktop 1>/dev/null 2>&1

echo "Step 3: load the image"
if [ -e /usr/bin/waydroid ];then
	sudo mv /var/lib/waydroid /tmp/waydroid 1>/dev/null 2>&1 && sudo rm -rf /tmp/waydroid 1>/dev/null 2>&1
fi

sudo tar -xf /usr/openfde/waydroid_image.tar -C /
echo 35 >> /tmp/fde_installing_process
sudo rm -rf /usr/openfde/waydroid_image.tar
echo 40 >> /tmp/fde_installing_process

if [ ! -e "/dev/fdeion" ];then
	sudo mkdir vendorimg
	sudo mount /usr/share/waydroid-extra/images/vendor.img vendorimg
	if [ $? != 0 ];then
		echo "Error: mount vendorimg failed"
		sudo rm -rf /usr/openfde
		exit 1
	fi
	sudo rm vendorimg/etc/vintf/manifest/android.hardware.graphics.allocator@4.0.img.xml 1>/dev/null 2>&1
	sudo rm vendorimg/etc/vintf/manifest/android.hardware.graphics.mapper@4.0-passthrough.img.xml 1>/dev/null 2>&1
	sudo rm vendorimg/etc/init/android.hardware.graphics.allocator@4.0-service.img.rc 1>/dev/null 2>&1
	sudo umount vendorimg
	sudo rmdir vendorimg 
fi	

sudo tar -xf /usr/openfde/waydroid.tar -C /
echo 45 >> /tmp/fde_installing_process
sudo rm -rf /usr/openfde/waydroid.tar
echo 50 >> /tmp/fde_installing_process

sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install  /usr/openfde/gbinder-python-1.0.0.tar.gz
echo 70 >> /tmp/fde_installing_process
sudo rm -rf /usr/openfde/gbinder-python-1.0.0.tar.gz

sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install pyclip --find-links=/usr/lib/waydroid/wheel
echo 80 >> /tmp/fde_installing_process
source /etc/os-release
sudo mv /usr/bin/fde_wm /tmp/fde_wm 1>/dev/null 2>&1 && sudo rm -rf /tmp/fde_wm 1>/dev/null 2>&1 
if [ "$ID" = "kylin" ];then
	sudo cp -a /usr/local/bin/mutter /usr/bin/fde_wm
else
	sudo cp -a /usr/bin/mutter /usr/bin/fde_wm
fi
echo 85 >> /tmp/fde_installing_process
sudo ldconfig
sudo systemctl daemon-reload 1>/dev/null 2>&1
sudo waydroid init -f
if [ $? != 0 ];then
	echo "Error: load image failed"
	exit 1
fi

echo 95 >> /tmp/fde_installing_process
sudo waydroid session stop 1>/dev/null 2>&1
sudo systemctl stop waydroid-container 1>/dev/null 2>&1
sudo sed -i "/fde.log/d" /etc/profile
sudo sed -i  '$a \export LOG_FILE=/var/log/fde.log'  /etc/profile
if [ ! -e /var/log/fde.log ];then
	sudo touch /var/log/fde.log
	sudo chmod a+wr /var/log/fde.log
fi
sudo mkdir -p /var/lib/fde/sockets
sudo chmod a+wrx /var/lib/fde/sockets
sudo touch /var/log/fde.log
sudo chmod a+wr /var/log/fde.log
echo 100 >> /tmp/fde_installing_process
sudo rm -rf /usr/openfde
sudo rm -rf  /tmp/fde_installing_process
echo "Congratulations, the installation success, please logout and then relogin to the OpenFDE"
